import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@fortawesome/fontawesome-svg-core/styles.css"; // Import FontAwesome CSS
import { config } from "@fortawesome/fontawesome-svg-core"; // Configure FontAwesome
import "./globals.css";
import { Analytics } from "@vercel/analytics/react"; // ✅ Add this line

// Custom fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Configure FontAwesome (disable auto-adding CSS)
config.autoAddCss = false;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
        <Analytics /> {/* ✅ Drop the analytics component here */}
      </body>
    </html>
  );
}
